package sudoku.solver;

import javax.swing.JOptionPane;

public class SudokuSolver extends javax.swing.JFrame {
    String casa[][] = new String[9][9];
    public SudokuSolver() {
        initComponents();
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        row4col9 = new javax.swing.JTextField();
        row4col8 = new javax.swing.JTextField();
        row5col2 = new javax.swing.JTextField();
        row5col1 = new javax.swing.JTextField();
        row5col7 = new javax.swing.JTextField();
        row5col4 = new javax.swing.JTextField();
        row5col5 = new javax.swing.JTextField();
        row5col3 = new javax.swing.JTextField();
        row5col6 = new javax.swing.JTextField();
        row5col9 = new javax.swing.JTextField();
        row1col8 = new javax.swing.JTextField();
        row5col8 = new javax.swing.JTextField();
        row2col2 = new javax.swing.JTextField();
        row6col2 = new javax.swing.JTextField();
        row2col1 = new javax.swing.JTextField();
        row9col1 = new javax.swing.JTextField();
        row2col7 = new javax.swing.JTextField();
        row9col7 = new javax.swing.JTextField();
        row2col4 = new javax.swing.JTextField();
        row9col4 = new javax.swing.JTextField();
        row2col5 = new javax.swing.JTextField();
        row9col5 = new javax.swing.JTextField();
        row2col3 = new javax.swing.JTextField();
        row2col6 = new javax.swing.JTextField();
        row2col9 = new javax.swing.JTextField();
        row2col8 = new javax.swing.JTextField();
        row1col2 = new javax.swing.JTextField();
        row1col1 = new javax.swing.JTextField();
        row1col7 = new javax.swing.JTextField();
        row1col4 = new javax.swing.JTextField();
        row1col5 = new javax.swing.JTextField();
        row1col3 = new javax.swing.JTextField();
        row1col6 = new javax.swing.JTextField();
        row1col9 = new javax.swing.JTextField();
        row9col3 = new javax.swing.JTextField();
        row9col6 = new javax.swing.JTextField();
        row9col9 = new javax.swing.JTextField();
        row9col8 = new javax.swing.JTextField();
        row3col2 = new javax.swing.JTextField();
        row7col2 = new javax.swing.JTextField();
        row3col1 = new javax.swing.JTextField();
        row7col1 = new javax.swing.JTextField();
        row3col7 = new javax.swing.JTextField();
        row7col7 = new javax.swing.JTextField();
        row3col4 = new javax.swing.JTextField();
        row7col4 = new javax.swing.JTextField();
        row3col5 = new javax.swing.JTextField();
        row7col5 = new javax.swing.JTextField();
        row3col3 = new javax.swing.JTextField();
        row7col3 = new javax.swing.JTextField();
        row3col6 = new javax.swing.JTextField();
        row3col9 = new javax.swing.JTextField();
        row3col8 = new javax.swing.JTextField();
        row6col1 = new javax.swing.JTextField();
        row7col6 = new javax.swing.JTextField();
        row7col9 = new javax.swing.JTextField();
        row7col8 = new javax.swing.JTextField();
        row8col2 = new javax.swing.JTextField();
        row6col7 = new javax.swing.JTextField();
        row8col1 = new javax.swing.JTextField();
        row6col4 = new javax.swing.JTextField();
        row8col7 = new javax.swing.JTextField();
        row6col5 = new javax.swing.JTextField();
        row8col4 = new javax.swing.JTextField();
        row6col3 = new javax.swing.JTextField();
        row8col5 = new javax.swing.JTextField();
        row6col6 = new javax.swing.JTextField();
        row8col3 = new javax.swing.JTextField();
        row6col9 = new javax.swing.JTextField();
        row8col6 = new javax.swing.JTextField();
        row6col8 = new javax.swing.JTextField();
        row4col2 = new javax.swing.JTextField();
        row4col1 = new javax.swing.JTextField();
        row4col7 = new javax.swing.JTextField();
        row8col9 = new javax.swing.JTextField();
        row8col8 = new javax.swing.JTextField();
        row9col2 = new javax.swing.JTextField();
        row4col4 = new javax.swing.JTextField();
        row4col5 = new javax.swing.JTextField();
        row4col3 = new javax.swing.JTextField();
        row4col6 = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioEasy = new javax.swing.JRadioButton();
        radioMedium = new javax.swing.JRadioButton();
        radioHard = new javax.swing.JRadioButton();
        radioExtreme = new javax.swing.JRadioButton();
        btnResetar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jLabel1.setText("Preencha os campos com um jogo válido para o computador resolver!");

        row4col9.setBackground(new java.awt.Color(204, 204, 204));
        row4col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col8.setBackground(new java.awt.Color(204, 204, 204));
        row4col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col2.setBackground(new java.awt.Color(204, 204, 204));
        row5col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col1.setBackground(new java.awt.Color(204, 204, 204));
        row5col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col7.setBackground(new java.awt.Color(204, 204, 204));
        row5col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col3.setBackground(new java.awt.Color(204, 204, 204));
        row5col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col9.setBackground(new java.awt.Color(204, 204, 204));
        row5col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row5col8.setBackground(new java.awt.Color(204, 204, 204));
        row5col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row5col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col2.setBackground(new java.awt.Color(204, 204, 204));
        row6col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col4.setBackground(new java.awt.Color(204, 204, 204));
        row2col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col4.setBackground(new java.awt.Color(204, 204, 204));
        row9col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col5.setBackground(new java.awt.Color(204, 204, 204));
        row2col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col5.setBackground(new java.awt.Color(204, 204, 204));
        row9col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col6.setBackground(new java.awt.Color(204, 204, 204));
        row2col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row2col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row2col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col4.setBackground(new java.awt.Color(204, 204, 204));
        row1col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col5.setBackground(new java.awt.Color(204, 204, 204));
        row1col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col6.setBackground(new java.awt.Color(204, 204, 204));
        row1col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row1col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row1col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col6.setBackground(new java.awt.Color(204, 204, 204));
        row9col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col4.setBackground(new java.awt.Color(204, 204, 204));
        row3col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col4.setBackground(new java.awt.Color(204, 204, 204));
        row7col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col5.setBackground(new java.awt.Color(204, 204, 204));
        row3col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col5.setBackground(new java.awt.Color(204, 204, 204));
        row7col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col6.setBackground(new java.awt.Color(204, 204, 204));
        row3col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row3col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row3col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col1.setBackground(new java.awt.Color(204, 204, 204));
        row6col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col6.setBackground(new java.awt.Color(204, 204, 204));
        row7col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row7col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row7col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col7.setBackground(new java.awt.Color(204, 204, 204));
        row6col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col4.setBackground(new java.awt.Color(204, 204, 204));
        row8col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col3.setBackground(new java.awt.Color(204, 204, 204));
        row6col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col5.setBackground(new java.awt.Color(204, 204, 204));
        row8col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col9.setBackground(new java.awt.Color(204, 204, 204));
        row6col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col6.setBackground(new java.awt.Color(204, 204, 204));
        row8col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row6col8.setBackground(new java.awt.Color(204, 204, 204));
        row6col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row6col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col2.setBackground(new java.awt.Color(204, 204, 204));
        row4col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col1.setBackground(new java.awt.Color(204, 204, 204));
        row4col1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col7.setBackground(new java.awt.Color(204, 204, 204));
        row4col7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row8col8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row8col8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row9col2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row9col2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col3.setBackground(new java.awt.Color(204, 204, 204));
        row4col3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        row4col6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        row4col6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEnviar.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sudoku.png"))); // NOI18N
        btnEnviar.setText("Resolver");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 32)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUDOKU SOLVER");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Os níveis Hard e Extreme ainda estão em desenvolvimento.</html>");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 2, 24)); // NOI18N
        jLabel4.setText("Exemplos:");

        radioEasy.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        radioEasy.setText("Easy");
        radioEasy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioEasyMouseClicked(evt);
            }
        });

        radioMedium.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        radioMedium.setText("Medium");
        radioMedium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioMediumMouseClicked(evt);
            }
        });

        radioHard.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        radioHard.setText("Hard");
        radioHard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioHardMouseClicked(evt);
            }
        });

        radioExtreme.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        radioExtreme.setText("Extreme");
        radioExtreme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioExtremeMouseClicked(evt);
            }
        });

        btnResetar.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        btnResetar.setText("Resetar");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioHard)
                                    .addComponent(radioMedium)
                                    .addComponent(radioEasy)
                                    .addComponent(jLabel4)
                                    .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioExtreme))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row1col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row1col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(row1col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row1col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row1col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row1col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row1col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row1col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row2col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(row2col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row3col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row3col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row3col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row3col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row3col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row3col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row3col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row4col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row4col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row4col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row4col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(row4col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row4col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(row5col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row5col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row5col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(row5col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row5col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row6col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(row6col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row6col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row6col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row6col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(row8col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row8col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row8col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row8col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(row8col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row8col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row9col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(row9col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(row9col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row8col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row5col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row9col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row9col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row7col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row4col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row9col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row6col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row2col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row7col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row7col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row6col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row2col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row5col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row2col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row7col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row6col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row8col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row7col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(row6col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(row3col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row3col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row9col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row2col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row9col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row7col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row9col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row5col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row7col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row5col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row7col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row2col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row4col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row4col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row8col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row2col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(230, 230, 230))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(276, 276, 276)
                            .addComponent(row7col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(radioEasy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioMedium)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioHard)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioExtreme)
                            .addGap(18, 18, 18)
                            .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(137, 137, 137)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row8col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row5col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row9col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row9col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row9col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row6col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row6col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row5col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row6col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row8col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(row6col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row3col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(row3col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row9col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(row9col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(row9col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row5col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(row5col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(row7col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row4col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(row4col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(row1col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(row8col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row1col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row1col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row1col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row2col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row2col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row3col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row3col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row3col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row3col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row3col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row3col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row3col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row4col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row4col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row4col4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row4col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row4col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row4col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row5col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row5col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row5col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row5col8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row5col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row6col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row6col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row6col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row6col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row6col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(row7col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row8col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row8col3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row8col5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row8col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row8col7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row8col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row9col2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row9col6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(row9col9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(row2col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(row4col1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        setTextArray();
        boolean permissaoHorizontal=true, permissaoQuadrado=true, permissaoVertical=true;
        boolean quadradoVerificado=false, completo=false, mudarNivel=false;
        int guardaLinha=0, guardaColuna=0, cont=0, tabuleiroValido=0;
        System.out.println("Total: " + total);
        while(!completo){
            for (int linha = 0; linha < casa.length; linha++) {
                for (int num = 1; num <= casa.length; num++) {
                    for (int coluna = 0; coluna < casa.length; coluna++) {
                        if (casa[linha][coluna].equals("")) {
                            //Verifica linha horizontal
                            for (int antes = 0; antes < coluna; antes++) {
                                if (casa[linha][antes].equals(Integer.toString(num))) {
                                    permissaoHorizontal = false;
                                    break;
                                }
                                permissaoHorizontal=true;
                            }
                            if (permissaoHorizontal) {
                                for (int depois = coluna + 1; depois < casa.length; depois++) {
                                    if (casa[linha][depois].equals(Integer.toString(num))) {
                                        permissaoHorizontal = false;
                                        break;
                                    }
                                    permissaoHorizontal=true;
                                }
                            }

                            //Verifica linha vertical
                            for (int cima = 0; cima < linha; cima++) {
                                if (casa[cima][coluna].equals(Integer.toString(num))) {
                                    permissaoVertical = false;
                                    break;
                                }
                                permissaoVertical = true;
                            }
                            if (permissaoVertical) {
                                for (int baixo = linha + 1; baixo < casa.length; baixo++) {
                                    if (casa[baixo][coluna].equals(Integer.toString(num))) {
                                        permissaoVertical = false;
                                        break;
                                    }
                                    permissaoVertical = true;
                                }
                            }

                            //Verifica quadrado
                            for (int i = 2; i < 9; i += 3) {
                                for (int j = 2; j < 9; j += 3) {
                                    if (linha <= i && coluna <= j) {
                                        for (int linhaQ = i - 2; linhaQ <= i; linhaQ++) {
                                            for (int colunaQ = j - 2; colunaQ <= j; colunaQ++) {
                                                if (casa[linhaQ][colunaQ].equals(Integer.toString(num))) {
                                                    permissaoQuadrado = false;
                                                    break;
                                                }
                                            }
                                            if (permissaoQuadrado==false) {
                                                break;
                                            }
                                        }
                                        quadradoVerificado=true;
                                        break;
                                    }
                                }
                                if (quadradoVerificado) {
                                    break;
                                }
                            }
                            //System.out.println("H: " + permissaoHorizontal);
                            //System.out.println("V: " + permissaoVertical);
                            //System.out.println("Q: " + permissaoQuadrado+"\n");
                            if (permissaoHorizontal && permissaoVertical && permissaoQuadrado) {
                                cont++;
                                if (cont == 1) {
                                    guardaLinha = linha;
                                    guardaColuna = coluna;
                                } else if(mudarNivel==false){
                                    guardaLinha = 0;
                                    guardaColuna = 0;
                                } else {

                                }
                            }
                            permissaoHorizontal=true;
                            permissaoVertical=true;
                            permissaoQuadrado=true;
                            quadradoVerificado=false;
                        }
                    }
                    if (cont == 1) {
                        casa[guardaLinha][guardaColuna] = Integer.toString(num);
                        tabuleiroValido++;
                    }
                    cont = 0;
                }

            }
            completo=true;
            for (String[] valor : casa) {
                for (int verificaColuna = 0; verificaColuna < casa.length; verificaColuna++) {
                    if (valor[verificaColuna].equals("")) {
                        completo=false;
                        break;
                    }
                }
                if (completo==false) {
                    break;
                }
            }
            if(!completo && tabuleiroValido==0){
                mudarNivel=true;
            }
            if(tabuleiroValido==0){
//                completo=true;
                tabuleiroValido=-1;
                break;
            }
            tabuleiroValido=0;
        }
        if(tabuleiroValido==-1) {
            JOptionPane.showMessageDialog(null, "Não foi possível resolver!");
        }
        setTextTabela();
        total=0;
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void radioExtremeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioExtremeMouseClicked
        radioEasy.setSelected(false);
        radioMedium.setSelected(false);
        radioHard.setSelected(false);
        //Exemplo
        row1col1.setText("");
        row1col2.setText("");
        row1col3.setText("");
        row1col4.setText("4");
        row1col5.setText("");
        row1col6.setText("");
        row1col7.setText("6");
        row1col8.setText("8");
        row1col9.setText("1");

        row2col1.setText("");
        row2col2.setText("");
        row2col3.setText("");
        row2col4.setText("");
        row2col5.setText("2");
        row2col6.setText("");
        row2col7.setText("");
        row2col8.setText("");
        row2col9.setText("");

        row3col1.setText("");
        row3col2.setText("");
        row3col3.setText("4");
        row3col4.setText("7");
        row3col5.setText("");
        row3col6.setText("");
        row3col7.setText("");
        row3col8.setText("3");
        row3col9.setText("");

        row4col1.setText("5");
        row4col2.setText("");
        row4col3.setText("3");
        row4col4.setText("");
        row4col5.setText("");
        row4col6.setText("");
        row4col7.setText("");
        row4col8.setText("");
        row4col9.setText("");

        row5col1.setText("1");
        row5col2.setText("8");
        row5col3.setText("");
        row5col4.setText("");
        row5col5.setText("");
        row5col6.setText("");
        row5col7.setText("");
        row5col8.setText("5");
        row5col9.setText("3");

        row6col1.setText("");
        row6col2.setText("");
        row6col3.setText("");
        row6col4.setText("");
        row6col5.setText("");
        row6col6.setText("");
        row6col7.setText("2");
        row6col8.setText("");
        row6col9.setText("6");

        row7col1.setText("");
        row7col2.setText("7");
        row7col3.setText("");
        row7col4.setText("");
        row7col5.setText("");
        row7col6.setText("8");
        row7col7.setText("5");
        row7col8.setText("");
        row7col9.setText("");

        row8col1.setText("");
        row8col2.setText("");
        row8col3.setText("");
        row8col4.setText("");
        row8col5.setText("1");
        row8col6.setText("");
        row8col7.setText("");
        row8col8.setText("");
        row8col9.setText("");

        row9col1.setText("6");
        row9col2.setText("4");
        row9col3.setText("8");
        row9col4.setText("");
        row9col5.setText("");
        row9col6.setText("9");
        row9col7.setText("");
        row9col8.setText("");
        row9col9.setText("");
    }//GEN-LAST:event_radioExtremeMouseClicked

    private void radioHardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioHardMouseClicked
        radioEasy.setSelected(false);
        radioMedium.setSelected(false);
        radioExtreme.setSelected(false);
        //Exemplo
        row1col1.setText("");
        row1col2.setText("5");
        row1col3.setText("");
        row1col4.setText("");
        row1col5.setText("1");
        row1col6.setText("");
        row1col7.setText("");
        row1col8.setText("7");
        row1col9.setText("");

        row2col1.setText("");
        row2col2.setText("");
        row2col3.setText("");
        row2col4.setText("");
        row2col5.setText("");
        row2col6.setText("3");
        row2col7.setText("");
        row2col8.setText("");
        row2col9.setText("");

        row3col1.setText("8");
        row3col2.setText("");
        row3col3.setText("4");
        row3col4.setText("5");
        row3col5.setText("");
        row3col6.setText("");
        row3col7.setText("");
        row3col8.setText("9");
        row3col9.setText("3");

        row4col1.setText("7");
        row4col2.setText("");
        row4col3.setText("");
        row4col4.setText("1");
        row4col5.setText("");
        row4col6.setText("4");
        row4col7.setText("");
        row4col8.setText("");
        row4col9.setText("8");

        row5col1.setText("");
        row5col2.setText("");
        row5col3.setText("");
        row5col4.setText("");
        row5col5.setText("");
        row5col6.setText("");
        row5col7.setText("");
        row5col8.setText("");
        row5col9.setText("");

        row6col1.setText("1");
        row6col2.setText("");
        row6col3.setText("");
        row6col4.setText("9");
        row6col5.setText("");
        row6col6.setText("6");
        row6col7.setText("");
        row6col8.setText("");
        row6col9.setText("7");

        row7col1.setText("4");
        row7col2.setText("3");
        row7col3.setText("");
        row7col4.setText("");
        row7col5.setText("");
        row7col6.setText("8");
        row7col7.setText("9");
        row7col8.setText("");
        row7col9.setText("2");

        row8col1.setText("");
        row8col2.setText("");
        row8col3.setText("");
        row8col4.setText("6");
        row8col5.setText("");
        row8col6.setText("");
        row8col7.setText("");
        row8col8.setText("");
        row8col9.setText("");

        row9col1.setText("");
        row9col2.setText("2");
        row9col3.setText("");
        row9col4.setText("");
        row9col5.setText("3");
        row9col6.setText("");
        row9col7.setText("");
        row9col8.setText("6");
        row9col9.setText("");
    }//GEN-LAST:event_radioHardMouseClicked

    private void radioMediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioMediumMouseClicked
        radioEasy.setSelected(false);
        radioHard.setSelected(false);
        radioExtreme.setSelected(false);
        //Exemplo
        row1col1.setText("4");
        row1col2.setText("2");
        row1col3.setText("3");
        row1col4.setText("");
        row1col5.setText("");
        row1col6.setText("6");
        row1col7.setText("");
        row1col8.setText("");
        row1col9.setText("7");

        row2col1.setText("");
        row2col2.setText("");
        row2col3.setText("");
        row2col4.setText("");
        row2col5.setText("");
        row2col6.setText("4");
        row2col7.setText("");
        row2col8.setText("");
        row2col9.setText("6");

        row3col1.setText("6");
        row3col2.setText("");
        row3col3.setText("5");
        row3col4.setText("7");
        row3col5.setText("");
        row3col6.setText("");
        row3col7.setText("");
        row3col8.setText("");
        row3col9.setText("");

        row4col1.setText("");
        row4col2.setText("7");
        row4col3.setText("4");
        row4col4.setText("");
        row4col5.setText("8");
        row4col6.setText("");
        row4col7.setText("2");
        row4col8.setText("");
        row4col9.setText("3");

        row5col1.setText("");
        row5col2.setText("");
        row5col3.setText("");
        row5col4.setText("");
        row5col5.setText("");
        row5col6.setText("");
        row5col7.setText("");
        row5col8.setText("");
        row5col9.setText("");

        row6col1.setText("5");
        row6col2.setText("");
        row6col3.setText("6");
        row6col4.setText("");
        row6col5.setText("7");
        row6col6.setText("");
        row6col7.setText("9");
        row6col8.setText("1");
        row6col9.setText("");

        row7col1.setText("");
        row7col2.setText("");
        row7col3.setText("");
        row7col4.setText("");
        row7col5.setText("");
        row7col6.setText("7");
        row7col7.setText("3");
        row7col8.setText("");
        row7col9.setText("1");

        row8col1.setText("1");
        row8col2.setText("");
        row8col3.setText("");
        row8col4.setText("2");
        row8col5.setText("");
        row8col6.setText("");
        row8col7.setText("");
        row8col8.setText("");
        row8col9.setText("");

        row9col1.setText("3");
        row9col2.setText("");
        row9col3.setText("");
        row9col4.setText("6");
        row9col5.setText("");
        row9col6.setText("");
        row9col7.setText("7");
        row9col8.setText("4");
        row9col9.setText("8");
    }//GEN-LAST:event_radioMediumMouseClicked

    private void radioEasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioEasyMouseClicked
        radioMedium.setSelected(false);
        radioHard.setSelected(false);
        radioExtreme.setSelected(false);
        //Exemplo
        row1col1.setText("6");
        row1col2.setText("");
        row1col3.setText("");
        row1col4.setText("5");
        row1col5.setText("");
        row1col6.setText("");
        row1col7.setText("8");
        row1col8.setText("");
        row1col9.setText("2");

        row2col1.setText("");
        row2col2.setText("3");
        row2col3.setText("2");
        row2col4.setText("6");
        row2col5.setText("");
        row2col6.setText("1");
        row2col7.setText("");
        row2col8.setText("9");
        row2col9.setText("");

        row3col1.setText("1");
        row3col2.setText("");
        row3col3.setText("");
        row3col4.setText("");
        row3col5.setText("2");
        row3col6.setText("");
        row3col7.setText("");
        row3col8.setText("3");
        row3col9.setText("");

        row4col1.setText("");
        row4col2.setText("8");
        row4col3.setText("");
        row4col4.setText("");
        row4col5.setText("1");
        row4col6.setText("");
        row4col7.setText("");
        row4col8.setText("6");
        row4col9.setText("5");

        row5col1.setText("");
        row5col2.setText("");
        row5col3.setText("7");
        row5col4.setText("3");
        row5col5.setText("");
        row5col6.setText("5");
        row5col7.setText("9");
        row5col8.setText("");
        row5col9.setText("");

        row6col1.setText("9");
        row6col2.setText("1");
        row6col3.setText("");
        row6col4.setText("");
        row6col5.setText("7");
        row6col6.setText("");
        row6col7.setText("");
        row6col8.setText("8");
        row6col9.setText("");

        row7col1.setText("");
        row7col2.setText("9");
        row7col3.setText("");
        row7col4.setText("");
        row7col5.setText("5");
        row7col6.setText("");
        row7col7.setText("");
        row7col8.setText("");
        row7col9.setText("8");

        row8col1.setText("");
        row8col2.setText("2");
        row8col3.setText("");
        row8col4.setText("9");
        row8col5.setText("");
        row8col6.setText("8");
        row8col7.setText("6");
        row8col8.setText("7");
        row8col9.setText("");

        row9col1.setText("3");
        row9col2.setText("");
        row9col3.setText("8");
        row9col4.setText("");
        row9col5.setText("");
        row9col6.setText("2");
        row9col7.setText("");
        row9col8.setText("");
        row9col9.setText("9");
    }//GEN-LAST:event_radioEasyMouseClicked

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        for (String[] valor : casa) {
            for (int i = 0; i < casa.length; i++) {
                valor[i] = "";
            }
        }
        setTextTabela();
        radioEasy.setSelected(false);
        radioMedium.setSelected(false);
        radioHard.setSelected(false);
        radioExtreme.setSelected(false);
    }//GEN-LAST:event_btnResetarActionPerformed
        
    private void setTextTabela() {
        row1col1.setText(casa[0][0]);
        row1col2.setText(casa[0][1]);
        row1col3.setText(casa[0][2]);
        row1col4.setText(casa[0][3]);
        row1col5.setText(casa[0][4]);
        row1col6.setText(casa[0][5]);
        row1col7.setText(casa[0][6]);
        row1col8.setText(casa[0][7]);
        row1col9.setText(casa[0][8]);
        
        row2col1.setText(casa[1][0]);
        row2col2.setText(casa[1][1]);
        row2col3.setText(casa[1][2]);
        row2col4.setText(casa[1][3]);
        row2col5.setText(casa[1][4]);
        row2col6.setText(casa[1][5]);
        row2col7.setText(casa[1][6]);
        row2col8.setText(casa[1][7]);
        row2col9.setText(casa[1][8]);
        
        row3col1.setText(casa[2][0]);
        row3col2.setText(casa[2][1]);
        row3col3.setText(casa[2][2]);
        row3col4.setText(casa[2][3]);
        row3col5.setText(casa[2][4]);
        row3col6.setText(casa[2][5]);
        row3col7.setText(casa[2][6]);
        row3col8.setText(casa[2][7]);
        row3col9.setText(casa[2][8]);

        row4col1.setText(casa[3][0]);
        row4col2.setText(casa[3][1]);
        row4col3.setText(casa[3][2]);
        row4col4.setText(casa[3][3]);
        row4col5.setText(casa[3][4]);
        row4col6.setText(casa[3][5]);
        row4col7.setText(casa[3][6]);
        row4col8.setText(casa[3][7]);
        row4col9.setText(casa[3][8]);
        
        row5col1.setText(casa[4][0]);
        row5col2.setText(casa[4][1]);
        row5col3.setText(casa[4][2]);
        row5col4.setText(casa[4][3]);
        row5col5.setText(casa[4][4]);
        row5col6.setText(casa[4][5]);
        row5col7.setText(casa[4][6]);
        row5col8.setText(casa[4][7]);
        row5col9.setText(casa[4][8]);
        
        row6col1.setText(casa[5][0]);
        row6col2.setText(casa[5][1]);
        row6col3.setText(casa[5][2]);
        row6col4.setText(casa[5][3]);
        row6col5.setText(casa[5][4]);
        row6col6.setText(casa[5][5]);
        row6col7.setText(casa[5][6]);
        row6col8.setText(casa[5][7]);
        row6col9.setText(casa[5][8]);
        
        row7col1.setText(casa[6][0]);
        row7col2.setText(casa[6][1]);
        row7col3.setText(casa[6][2]);
        row7col4.setText(casa[6][3]);
        row7col5.setText(casa[6][4]);
        row7col6.setText(casa[6][5]);
        row7col7.setText(casa[6][6]);
        row7col8.setText(casa[6][7]);
        row7col9.setText(casa[6][8]);
        
        row8col1.setText(casa[7][0]);
        row8col2.setText(casa[7][1]);
        row8col3.setText(casa[7][2]);
        row8col4.setText(casa[7][3]);
        row8col5.setText(casa[7][4]);
        row8col6.setText(casa[7][5]);
        row8col7.setText(casa[7][6]);
        row8col8.setText(casa[7][7]);
        row8col9.setText(casa[7][8]);
        
        row9col1.setText(casa[8][0]);
        row9col2.setText(casa[8][1]);
        row9col3.setText(casa[8][2]);
        row9col4.setText(casa[8][3]);
        row9col5.setText(casa[8][4]);
        row9col6.setText(casa[8][5]);
        row9col7.setText(casa[8][6]);
        row9col8.setText(casa[8][7]);
        row9col9.setText(casa[8][8]);
    }
    
    int total=0;
    private void setTextArray() {
        casa[0][0] = row1col1.getText();
        casa[0][1] = row1col2.getText();
        casa[0][2] = row1col3.getText();
        casa[0][3] = row1col4.getText();
        casa[0][4] = row1col5.getText();
        casa[0][5] = row1col6.getText();
        casa[0][6] = row1col7.getText();
        casa[0][7] = row1col8.getText();
        casa[0][8] = row1col9.getText();
 
        casa[1][0] = row2col1.getText();
        casa[1][1] = row2col2.getText();
        casa[1][2] = row2col3.getText();
        casa[1][3] = row2col4.getText();
        casa[1][4] = row2col5.getText();
        casa[1][5] = row2col6.getText();
        casa[1][6] = row2col7.getText();
        casa[1][7] = row2col8.getText();
        casa[1][8] = row2col9.getText();
        
        casa[2][0] = row3col1.getText();
        casa[2][1] = row3col2.getText();
        casa[2][2] = row3col3.getText();
        casa[2][3] = row3col4.getText();
        casa[2][4] = row3col5.getText();
        casa[2][5] = row3col6.getText();
        casa[2][6] = row3col7.getText();
        casa[2][7] = row3col8.getText();
        casa[2][8] = row3col9.getText();
        
        casa[3][0] = row4col1.getText();
        casa[3][1] = row4col2.getText();
        casa[3][2] = row4col3.getText();
        casa[3][3] = row4col4.getText();
        casa[3][4] = row4col5.getText();
        casa[3][5] = row4col6.getText();
        casa[3][6] = row4col7.getText();
        casa[3][7] = row4col8.getText();
        casa[3][8] = row4col9.getText();
        
        casa[4][0] = row5col1.getText();
        casa[4][1] = row5col2.getText();
        casa[4][2] = row5col3.getText();
        casa[4][3] = row5col4.getText();
        casa[4][4] = row5col5.getText();
        casa[4][5] = row5col6.getText();
        casa[4][6] = row5col7.getText();
        casa[4][7] = row5col8.getText();
        casa[4][8] = row5col9.getText();
        
        casa[5][0] = row6col1.getText();
        casa[5][1] = row6col2.getText();
        casa[5][2] = row6col3.getText();
        casa[5][3] = row6col4.getText();
        casa[5][4] = row6col5.getText();
        casa[5][5] = row6col6.getText();
        casa[5][6] = row6col7.getText();
        casa[5][7] = row6col8.getText();
        casa[5][8] = row6col9.getText();
        
        casa[6][0] = row7col1.getText();
        casa[6][1] = row7col2.getText();
        casa[6][2] = row7col3.getText();
        casa[6][3] = row7col4.getText();
        casa[6][4] = row7col5.getText();
        casa[6][5] = row7col6.getText();
        casa[6][6] = row7col7.getText();
        casa[6][7] = row7col8.getText();
        casa[6][8] = row7col9.getText();
        
        casa[7][0] = row8col1.getText();
        casa[7][1] = row8col2.getText();
        casa[7][2] = row8col3.getText();
        casa[7][3] = row8col4.getText();
        casa[7][4] = row8col5.getText();
        casa[7][5] = row8col6.getText();
        casa[7][6] = row8col7.getText();
        casa[7][7] = row8col8.getText();
        casa[7][8] = row8col9.getText();
        
        casa[8][0] = row9col1.getText();
        casa[8][1] = row9col2.getText();
        casa[8][2] = row9col3.getText();
        casa[8][3] = row9col4.getText();
        casa[8][4] = row9col5.getText();
        casa[8][5] = row9col6.getText();
        casa[8][6] = row9col7.getText();
        casa[8][7] = row9col8.getText();
        casa[8][8] = row9col9.getText();
        
        for (String[] valor : casa) {
            for (int i = 0; i < casa.length; i++) {
                if(!valor[i].equals("")) {
                    total++;
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuSolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnResetar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton radioEasy;
    private javax.swing.JRadioButton radioExtreme;
    private javax.swing.JRadioButton radioHard;
    private javax.swing.JRadioButton radioMedium;
    private javax.swing.JTextField row1col1;
    private javax.swing.JTextField row1col2;
    private javax.swing.JTextField row1col3;
    private javax.swing.JTextField row1col4;
    private javax.swing.JTextField row1col5;
    private javax.swing.JTextField row1col6;
    private javax.swing.JTextField row1col7;
    private javax.swing.JTextField row1col8;
    private javax.swing.JTextField row1col9;
    private javax.swing.JTextField row2col1;
    private javax.swing.JTextField row2col2;
    private javax.swing.JTextField row2col3;
    private javax.swing.JTextField row2col4;
    private javax.swing.JTextField row2col5;
    private javax.swing.JTextField row2col6;
    private javax.swing.JTextField row2col7;
    private javax.swing.JTextField row2col8;
    private javax.swing.JTextField row2col9;
    private javax.swing.JTextField row3col1;
    private javax.swing.JTextField row3col2;
    private javax.swing.JTextField row3col3;
    private javax.swing.JTextField row3col4;
    private javax.swing.JTextField row3col5;
    private javax.swing.JTextField row3col6;
    private javax.swing.JTextField row3col7;
    private javax.swing.JTextField row3col8;
    private javax.swing.JTextField row3col9;
    private javax.swing.JTextField row4col1;
    private javax.swing.JTextField row4col2;
    private javax.swing.JTextField row4col3;
    private javax.swing.JTextField row4col4;
    private javax.swing.JTextField row4col5;
    private javax.swing.JTextField row4col6;
    private javax.swing.JTextField row4col7;
    private javax.swing.JTextField row4col8;
    private javax.swing.JTextField row4col9;
    private javax.swing.JTextField row5col1;
    private javax.swing.JTextField row5col2;
    private javax.swing.JTextField row5col3;
    private javax.swing.JTextField row5col4;
    private javax.swing.JTextField row5col5;
    private javax.swing.JTextField row5col6;
    private javax.swing.JTextField row5col7;
    private javax.swing.JTextField row5col8;
    private javax.swing.JTextField row5col9;
    private javax.swing.JTextField row6col1;
    private javax.swing.JTextField row6col2;
    private javax.swing.JTextField row6col3;
    private javax.swing.JTextField row6col4;
    private javax.swing.JTextField row6col5;
    private javax.swing.JTextField row6col6;
    private javax.swing.JTextField row6col7;
    private javax.swing.JTextField row6col8;
    private javax.swing.JTextField row6col9;
    private javax.swing.JTextField row7col1;
    private javax.swing.JTextField row7col2;
    private javax.swing.JTextField row7col3;
    private javax.swing.JTextField row7col4;
    private javax.swing.JTextField row7col5;
    private javax.swing.JTextField row7col6;
    private javax.swing.JTextField row7col7;
    private javax.swing.JTextField row7col8;
    private javax.swing.JTextField row7col9;
    private javax.swing.JTextField row8col1;
    private javax.swing.JTextField row8col2;
    private javax.swing.JTextField row8col3;
    private javax.swing.JTextField row8col4;
    private javax.swing.JTextField row8col5;
    private javax.swing.JTextField row8col6;
    private javax.swing.JTextField row8col7;
    private javax.swing.JTextField row8col8;
    private javax.swing.JTextField row8col9;
    private javax.swing.JTextField row9col1;
    private javax.swing.JTextField row9col2;
    private javax.swing.JTextField row9col3;
    private javax.swing.JTextField row9col4;
    private javax.swing.JTextField row9col5;
    private javax.swing.JTextField row9col6;
    private javax.swing.JTextField row9col7;
    private javax.swing.JTextField row9col8;
    private javax.swing.JTextField row9col9;
    // End of variables declaration//GEN-END:variables
}
